# Generated by Django 3.2.3 on 2021-05-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ClothingSex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сlothing',
            new_name='Clothing',
        ),
        migrations.RenameModel(
            old_name='СlothingSex',
            new_name='ClothingSex',
        ),
        migrations.RenameModel(
            old_name='СlothingType',
            new_name='ClothingType',
        ),
    ]
